### ISSUE TITLE
Text decoration line-through is not working

### ISSUE THREAD

**Issue by CATFED** [nhn/tui.image-editor#453] opened 2020-09-17 12:09 UTC
**Describe the bug**
Property text-decoration: line-throught is not working for text;

I am trying run code for example - imageEditor.changeTextStyle(2, {textDecoration: 'line-through'});  but is not working. For underline and overline is working.

**Comment by jinwoo-kim-nhn** [comment] 2020-09-23 01:38
Thanks for letting me know. I'll check.

**Comment by kittychengyuenpui** [comment] 2020-09-29 05:43
In src/js/component/text.js file, it seems to be a typo for line-through in **_getTextDecorationAdaptObject** method:
`linetrought: textDecoration === 'line-through',`

In my case, if I changed that line to `linethrough: textDecoration === 'line-through',` and add a case in $btnTextStyle onclick event handler with `styleObj = { linethrough: true };` and it seems to work.
You may try to change that line and use `imageEditor.changeTextStyle(2, {linethrough: true});` and see if it works?
However, I am not sure if it works in your case as well.

**Comment by CATFED** [comment] 2020-09-29 09:33
> In my case, if I changed that line to linethrough: textDecoration === 'line-through', and add a case in $btnTextStyle onclick event handler with styleObj = { linethrough: true }; and it seems to work.
You may try to change that line and use imageEditor.changeTextStyle(2, {linethrough: true}); and see if it works?
However, I am not sure if it works in your case as well.

Yes, it works! Thank you very much! But in documentation not written about it moment.

**Comment by CATFED** [comment] 2020-09-29 09:34
> In my case (using the tui-image-editor.js (version 3.10.0) and service-basic.js), if I changed that line to linethrough: textDecoration === 'line-through', and add a case in $btnTextStyle onclick event handler with styleObj = { linethrough: true }; and it seems to work.
You may try to change that line and use imageEditor.changeTextStyle(2, {linethrough: true}); and see if it works?
However, I am not sure if it works in your case as well.

Yes, it works! Thank you very much! But in documentation not written about this moment.

**Comment by kittychengyuenpui** [comment] 2020-10-05 03:00
> > In my case (using the tui-image-editor.js (version 3.10.0) and service-basic.js), if I changed that line to linethrough: textDecoration === 'line-through', and add a case in $btnTextStyle onclick event handler with styleObj = { linethrough: true }; and it seems to work.
> > You may try to change that line and use imageEditor.changeTextStyle(2, {linethrough: true}); and see if it works?
> > However, I am not sure if it works in your case as well.
> 
> Yes, it works! Thank you very much! But in documentation not written about this moment.

I just traced back to that file and found that typo which I assumed is the cause of line-through not working. But then I guess overline and strikethrough are not commonly used, so the documentation did not mention about other choices for textDecoration other than underline...

**Comment by mlongv** [comment] 2020-10-15 05:45
thank for your help.Finally, it's done.

**Comment by lja1018** [comment] 2020-12-09 03:26
@CATFED 
This issue was resolved in v3.11.0. Thank you!

**Closed by lja1018** 2020-12-09 03:26 UTC
Labels: Bug
