### ISSUE TITLE
Draw tool issue #1 - strokes change its position by itself

### ISSUE THREAD

**Issue by onadein** [nhn/tui.image-editor#228] opened 2019-07-22 14:20 UTC
## Version
3.5.3 and 3.6.0

## Development Environment
Chrome, Windows

## Current Behavior
1. Go to http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi/
2. Select Draw tool.
3. Draw first stoke.
4. When starting to draw second stroke - first stroke moved.
5. When starting to draw third stroke - second stroke moved.
etc. 
See screen capture attached.
![draw_tool_issue_1](https://user-images.githubusercontent.com/4040019/61639866-f8c84800-aca4-11e9-95aa-696e52c541f4.gif)
[draw_tool_issue_1.zip](https://github.com/nhn/tui.image-editor/files/3417844/draw_tool_issue_1.zip)

## Expected Behavior
Previous strokes shouldn't change its position when drawing some more ones.

**Comment by ThierryNapspirit** [comment] 2019-07-23 15:41
Same issue on Linux: Chrome and Firefox.

**Comment by ThierryNapspirit** [comment] 2019-07-25 09:25
May be a bug / regression from fabric.js
I have found this similar issue: [https://github.com/fabricjs/fabric.js/issues/5705](https://github.com/fabricjs/fabric.js/issues/5705l)

**Comment by ThierryNapspirit** [comment] 2019-07-25 09:50
Test with frabric 1.7.20 (last release before 2.0.0): we do have the same issue.

**Comment by shreyanshsheth26** [comment] 2019-07-29 09:39
I am facing same issue in angular 8 version,
i have installed fabric  "fabric": "^3.3.0-browser",

**Comment by jiyangmax** [comment] 2019-07-30 12:00
How can I fix it?

**Comment by junghwan-park** [comment] 2019-08-01 09:21
I checked this issue very briefly, I think fabric.js and ImageEditor's canvas dimension is not synchronized. Fabric.js re-render already rendered free drawing lines when new line has to first render. Already rendered free drawing line's position was slightly mismatched.

I'll dig down this issue and find out what's the exact reason of free drawing line jumping.

**Comment by treztreiz** [comment] 2019-09-24 19:15
Hey, is there a fix for this bug ? Thank you.

**Comment by aldrashan** [comment] 2019-10-03 05:34
> Hey, is there a fix for this bug ? Thank you.

Or can anyone tell us what the latest compatible versions that don't have bugs are?

**Comment by treztreiz** [comment] 2019-10-03 09:48
> > Hey, is there a fix for this bug ? Thank you.
> 
> Or can anyone tell us what the latest compatible versions that don't have bugs are?

Using the 1.6.7 version of fabric.js seems to prevent this bug.
https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.6.7/fabric.min.js

**Comment by sphildreth** [comment] 2019-10-04 15:22
> > > Hey, is there a fix for this bug ? Thank you.
> > 
> > 
> > Or can anyone tell us what the latest compatible versions that don't have bugs are?
> 
> Using the 1.6.7 version of fabric.js seems to prevent this bug.
> https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.6.7/fabric.min.js

Be aware with this 1.6.7 fabric version several of the filters (Greytone, Sepia, Vintage, etc.) don't seem to work the same (invalid parameter exceptions get thrown) as current fabric version.

**Comment by aldrashan** [comment] 2019-10-07 06:25
> > > > Hey, is there a fix for this bug ? Thank you.
> > > 
> > > 
> > > Or can anyone tell us what the latest compatible versions that don't have bugs are?
> > 
> > 
> > Using the 1.6.7 version of fabric.js seems to prevent this bug.
> > https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.6.7/fabric.min.js
> 
> Be aware with this 1.6.7 fabric version several of the filters (Greytone, Sepia, Vintage, etc.) don't seem to work the same (invalid parameter exceptions get thrown) as current fabric version.

For some reason the drawing on mobile isn't working properly there either. Touch coordinates seem to "lag behind" i.e. touch coordinate starts at the correct position but starts to be incorrect when moving your finger around. Don't think it's getting scaled to the correct position properly when the canvas is larger than the screen size. Probably fixed in a later version but alas...

**Comment by Mater1996** [comment] 2019-10-09 01:53
I think it was caused by originX and originY being incorrectly set

in graphics.js
![image](https://user-images.githubusercontent.com/26322213/66445202-9b0ff480-ea78-11e9-9bf4-cc589eafb2f9.png) 

this is right

**Comment by rainbowcatcher** [comment] 2019-10-20 12:48
Is there a plan to fix this bug?

**Comment by aborja79** [comment] 2019-10-28 12:16
Is there any fix?

**Comment by ViniciusGularte** [comment] 2019-11-11 12:55
Any fix to this?

**Comment by jinwoo-kim-nhn** [comment] 2019-12-03 01:33
#280

**Closed** 2019-12-04 02:30 UTC
Labels: Bug

**Comment by jinwoo-kim-nhn** [comment] 2019-12-04 02:31
resolved at 3.7.1

**Comment by uttam9300** [comment] 2019-12-06 09:20
> I think it was caused by originX and originY being incorrectly set
> 
> in graphics.js
> 
> ```
> _onPathCreated(obj) {
> 
>         var SELECTION_STYLE = Object.assign({},consts.fObjectOptions.SELECTION_STYLE)
>         SELECTION_STYLE.originX = 'left'
>         SELECTION_STYLE.originY = 'top'
>         obj.path.set(SELECTION_STYLE);
>         const params = this.createObjectProperties(obj.path);
> 
>         this.fire(events.ADD_OBJECT, params);
>  }
> ```
> 
> this is right
 free drawing is continue drawing after mouseup.
ReferenceError: consts is not defined
    at Graphics._onPathCreated
