### ISSUE TITLE
3.15.1, Failed to compile.

### ISSUE THREAD

**Issue by huno2323** [nhn/tui.image-editor#664] opened 2021-10-19 04:42 UTC
![image](https://user-images.githubusercontent.com/43056738/137845212-f08b0a45-c855-4fd7-92ec-4046579c8744.png)

When compiling, a message that requires installation of the dependent module appears in the version of 3.15.1.
Can I check it?

**Comment by huno2323** [comment] 2021-10-19 04:46
I checked the USAGESTATISTACS option. TT

**Comment by lja1018** [comment] 2021-10-19 05:09
@huno2323 
Thank you for the question.
I think it's because the dependency position changed in 3.15.1.
Do you want to reinstall the dependencies in the root directory and image-editor?

**Comment by lja1018** [comment] 2021-10-19 06:12
@huno2323 
Thank you for the fast bug report.
I figured out the cause of the bug.
It will be resolved in version `3.15.2` and will be updated very quickly.
In the meantime, can you use `3.15.0` version?

**Comment by lja1018** [comment] 2021-10-20 05:22
@huno2323 
This error was corrected in `3.15.2` version.
Thank you for letting me know quickly. :)

**Closed by lja1018** 2021-10-20 05:22 UTC
Labels: Bug
